### ISSUE TITLE
Duplicates when sending to gmail addresses?

### ISSUE THREAD

**Issue by crazyman143** [bstascavage/plexReport#64]
First off: Happy to find your project. love it!
Question regarding possible bug: I am running this on debian and using the "recipients_email" option in the config file. I'm sending to specific emails and not to "friends" (With my setup I don't have any). I find that any email address with a gmail.com domain receives the email twice. Addresses with domains other than gmail.com only receive a single copy, as expected. Also I am sending from my gmail account, as supported. Any reason for this?

**Comment by Kazz3r24** [comment]
I had the same issue initially, but it was only my Gmail account that was receiving the duplicate email. I realized that it was sending to my Plex Account as well as my email only because I had my personal email in the recipient list. Not sure if you're issue is like this. Posting your log will help anyone contributing their efforts.

**Comment by crazyman143** [comment]
I thought that at first, too but I added a few other gmail accounts to the config file as well and all of them receive the duplicate email. Any addresses without an @gmail.com however, receive only one. 

Sorry for this noob question but how/where can I get a log? I'll post it here if I can find it. thanks!

**Comment by Kazz3r24** [comment]
That is strange indeed.. I only had that issue with my own personal gmail account getting duplicates because it was also sending to my plex account as well being tied to Gmail.
You can find the log files in /var/log/plexreport.log

simply enter the following command:

cat /var/log/plexreport.log 

P.S. if you've been running Plex Report for as long as I have, it's going to dump a lot of information into your terminal. So you can either pipe it into the less command 
"cat /var/log/plexreport.log | less" without the quotes.
 or even open and save the log file with gedit 
"gedit /var/log/plexreport.log" without the quotes.
 again depending on how large the log file is, it may take a few minutes to fully open the log.
For easy viewing I'd recommend the gedit approach and save the output as a .txt file as it'll be nicely formatted, and not a jumbled mess :P

**Comment by bstascavage** [comment]
What command line flags are you using?

**Comment by crazyman143** [comment]
Sorry for responding to this so very late- forgot about the issue. As it turns out, the others that were receiving duplicates WERE in my friends, and I'm just an idiot. I have added the -n option and all is well. Sorry to be a bother.
