### ISSUE TITLE
Missing Year for Movies

### ISSUE THREAD

**Issue by jjbmetal** [bstascavage/plexReport#86]
In the email sent out, the year does not display for movies.

Instead of this - Spider-Man: Homecoming (2017)
It shows this - Spider-Man: Homecoming ()

This happens for all movies.

**Comment by sgtcoder** [comment]
Same thing for me, the years don't show up in the emails.

**Comment by codermjb** [comment]
Do a nano and update the "Year" to "year" fixes the problem in bin/plexreport

https://github.com/bstascavage/plexReport/blob/master/bin/plexreport

 ``` :date        => omdb_result['Year'],```
to
 ``` :date        => omdb_result['year'],```

**Comment by sgtcoder** [comment]
After going through the code and all, they are passing back date as release_date rather than just year

https://api.themoviedb.org/3/movie/tt0765429?api_key=974eddb0f95ce2b912b9b37a63358823

**Comment by sgtcoder** [comment]
Sorry for all the messages but I got it figured out!

GOT IT: http://prntscr.com/it41vq

OMDB now requires a key.

Sign up for API Key here: http://www.omdbapi.com/apikey.aspx

Edit the omdb.rb and append api_key variable at the end
```new_query = '?i=' + query + '&plot=short&r=json&apikey={api_key}'```

**Comment by jjbmetal** [comment]
No problem, thanks for figuring this out, this is great!

I will get signed up for the api and change the query to get this working.

**Comment by sgtcoder** [comment]
@jjbmetal we should have the owner of the repo update this as well.

Also, are there any more updates on this repo? I am about to make some changes to some stuff and make a mini-detailed view so it is a cross between detailed view and simple detail. I want as much information going out to my Plex friends, but at the same time, I want to limit the fields that go out and change the format of the release date.

**Comment by jjbmetal** [comment]
@codermjb That would be great, but it looks like October was the last time there was an update.  Not sure how often their able to get to work on this.

I just installed on a new server in the last 2 months just pulling it down from this github.

**Comment by sgtcoder** [comment]
@jjbmetal let me know what you think of this. I forked this over and did some updates and improvements and changes I wanted to see: https://github.com/codermjb/plexReport

I cleaned up the email so if you have dozens of movies, GMail won't truncate the HTML and render is useless. And a few other changes.

**Comment by jjbmetal** [comment]
@codermjb Looked at the new fork.  I had done the for omdb.rb for the year fixm and had already started to poke around in email_body.erb to add a field and en.yml to change some wording I wanted, like the thank you message.

I like the idea of it not truncating in gmail.  I was looking at your update to email_body.erb  You stripped a lot out, is none of the table/style stuff necessary that was in the original? And does it still look the same and size well to different devices?

Should this discussion port to your fork, or is that not available for a fork?  I did not see a place for a comment/issue to type anything out.

**Comment by sgtcoder** [comment]
@jjbmetal thank you for looking at the fork. Yes, there was a lot of html in there, in fact, it was redundant and overdone. It did look great though, I agree, but that could have been done simpler with less code. He also made it responsive and styled it in detail so that's a plus. I tried to keep it look like the same as his, but with a fraction of the HTML. And I am not a professional CSS/HTML email template guy, but I don't need anything extreme. I just need it to look good, simple code, and to load in full. And I think I did a pretty good job. I could only get like 5 items on his, and now I have over 35 items on mine that load full detailed. I fixed spaces and capitalization too. We have access to API's so we could even add more data, only thing is, it's still an email and no one wants to scroll for days. If they like it they can click the link and view videos and details from IMDB.

Screenshots
http://prntscr.com/iu4don
http://prntscr.com/iu4drg

And you should be able to just open a new issue on the fork if you want. Since this repo looks abandoned (and a lot of the other forks of this are abandoned too).

You are welcome to send feedback. I might implement some cool stuff and improve it more. I use this weekly and the first official emails go out this Friday.

**Comment by sgtcoder** [comment]
Ahh, I had to enable Issues for the Fork. I guess it's disabled by default when you fork a project over.
